"""Seyahat Asistanı > Acil Çeviri için Türkçe-İngilizce hazır cümle verisi.

Her kategori (key, çeviri etiketi, [(türkçe, ingilizce), ...]) şeklindedir.
Sadece bu dosyayı düzenleyerek yeni kategori/cümle eklenebilir.
"""

EMERGENCY_CATEGORIES = [
    (
        "medical",
        "travel.emergency.cat.medical",
        [
            ("Yardım edin, lütfen!", "Help me, please!"),
            ("Ambulans çağırın!", "Call an ambulance!"),
            ("Doktora ihtiyacım var.", "I need a doctor."),
            ("En yakın hastane nerede?", "Where is the nearest hospital?"),
            ("Penisiline alerjim var.", "I'm allergic to penicillin."),
            ("Göğsümde ağrı var.", "I have chest pain."),
            ("Nefes alamıyorum.", "I can't breathe."),
            ("İlaçlarımı kaybettim.", "I lost my medication."),
            ("Sağlık sigortam var.", "I have health insurance."),
        ],
    ),
    (
        "police",
        "travel.emergency.cat.police",
        [
            ("Polis çağırın!", "Call the police!"),
            ("Çantam çalındı.", "My bag was stolen."),
            ("Kayboldum.", "I am lost."),
            ("Pasaportumu kaybettim.", "I lost my passport."),
            ("Türk Konsolosluğu'nu aramam gerekiyor.", "I need to call the Turkish Consulate."),
            ("Bir kaza oldu.", "There has been an accident."),
            ("Kendimi güvende hissetmiyorum.", "I don't feel safe."),
            ("Bir avukatla konuşmak istiyorum.", "I want to speak to a lawyer."),
        ],
    ),
    (
        "airport",
        "travel.emergency.cat.airport",
        [
            ("Uçağımı kaçırdım.", "I missed my flight."),
            ("Bagajım kayboldu.", "My luggage is lost."),
            ("Aktarma uçuşum var.", "I have a connecting flight."),
            ("İşte pasaportum ve vizem.", "Here is my passport and visa."),
            ("Ziyaret amacım turizm.", "The purpose of my visit is tourism."),
            ("Gümrükte beyan edecek bir şeyim yok.", "I have nothing to declare."),
            ("Uçuşum ertelendi.", "My flight has been delayed."),
        ],
    ),
    (
        "hotel",
        "travel.emergency.cat.hotel",
        [
            ("Rezervasyonum var.", "I have a reservation."),
            ("Oda anahtarımı kaybettim.", "I lost my room key."),
            ("Odamda sıcak su yok.", "There is no hot water in my room."),
            ("Faturamı görebilir miyim?", "Can I see my bill, please?"),
            ("Bagajımı saklayabilir misiniz?", "Can you store my luggage, please?"),
            ("Bana bir taksi çağırabilir misiniz?", "Can you call me a taxi, please?"),
        ],
    ),
    (
        "restaurant",
        "travel.emergency.cat.restaurant",
        [
            ("Menüyü görebilir miyim?", "Can I see the menu, please?"),
            ("Fıstık alerjim var.", "I have a peanut allergy."),
            ("Vejetaryen bir seçenek var mı?", "Is there a vegetarian option?"),
            ("Hesabı alabilir miyim?", "Can I have the check, please?"),
            ("Biraz su alabilir miyim?", "Can I have some water, please?"),
        ],
    ),
    (
        "general",
        "travel.emergency.cat.general",
        [
            ("Bu adrese nasıl giderim?", "How do I get to this address?"),
            ("En yakın eczane nerede?", "Where is the nearest pharmacy?"),
            ("Tuvalet nerede?", "Where is the restroom?"),
            ("Wi-Fi şifresi nedir?", "What is the Wi-Fi password?"),
            ("Yardımcı olabilir misiniz?", "Can you help me, please?"),
            ("Türkçe bilen biri var mı?", "Does anyone speak Turkish?"),
            ("Anlamıyorum.", "I don't understand."),
            ("Daha yavaş konuşabilir misiniz?", "Could you speak more slowly, please?"),
        ],
    ),
]

# Seyahat Asistanı > Genel Konuşma Kılavuzu için Türkçe-İngilizce cümle verisi.
# Acil Çeviri'nin aksine kriz odaklı değil, günlük seyahat sohbetlerine yöneliktir.
PHRASEBOOK_CATEGORIES = [
    (
        "greetings",
        "travel.phrasebook.cat.greetings",
        [
            ("Merhaba.", "Hello."),
            ("Günaydın.", "Good morning."),
            ("İyi akşamlar.", "Good evening."),
            ("Nasılsınız?", "How are you?"),
            ("İyiyim, teşekkürler.", "I'm fine, thank you."),
            ("Teşekkür ederim.", "Thank you."),
            ("Rica ederim.", "You're welcome."),
            ("Lütfen.", "Please."),
            ("Affedersiniz.", "Excuse me."),
            ("Evet.", "Yes."),
            ("Hayır.", "No."),
            ("Görüşürüz.", "Goodbye."),
            ("Adım ...", "My name is ..."),
            ("İngilizce biliyor musunuz?", "Do you speak English?"),
        ],
    ),
    (
        "directions",
        "travel.phrasebook.cat.directions",
        [
            ("En yakın otobüs durağı nerede?", "Where is the nearest bus stop?"),
            ("Bu tren nereye gidiyor?", "Where does this train go?"),
            ("Bilet nereden alabilirim?", "Where can I buy a ticket?"),
            ("Buraya nasıl giderim?", "How do I get here?"),
            ("Sağa dönün.", "Turn right."),
            ("Sola dönün.", "Turn left."),
            ("Doğru gidin.", "Go straight ahead."),
            ("Ne kadar sürer?", "How long does it take?"),
            ("Bir taksi çağırabilir misiniz?", "Can you call me a taxi, please?"),
            ("Havaalanına ne kadar uzak?", "How far is the airport?"),
            ("Bu otobüs merkeze gidiyor mu?", "Does this bus go to the city center?"),
        ],
    ),
    (
        "shopping",
        "travel.phrasebook.cat.shopping",
        [
            ("Bu ne kadar?", "How much is this?"),
            ("Çok pahalı.", "That's too expensive."),
            ("Kredi kartı geçiyor mu?", "Do you accept credit cards?"),
            ("Sadece bakıyorum, teşekkürler.", "I'm just looking, thank you."),
            ("Bunu deneyebilir miyim?", "Can I try this on?"),
            ("Daha küçük bedeni var mı?", "Do you have a smaller size?"),
            ("Daha büyük bedeni var mı?", "Do you have a bigger size?"),
            ("Fiş alabilir miyim?", "Can I have a receipt, please?"),
            ("İndirim var mı?", "Is there a discount?"),
            ("Bunu alıyorum.", "I'll take this."),
        ],
    ),
    (
        "dining",
        "travel.phrasebook.cat.dining",
        [
            ("Bir masa ayırtmak istiyorum.", "I'd like to reserve a table."),
            ("Menüyü görebilir miyim?", "Can I see the menu, please?"),
            ("Bu yemekte ne var?", "What's in this dish?"),
            ("Az pişmiş olsun.", "Rare, please."),
            ("İyi pişmiş olsun.", "Well done, please."),
            ("Vejetaryen bir seçenek var mı?", "Is there a vegetarian option?"),
            ("Şerefe!", "Cheers!"),
            ("Afiyet olsun.", "Enjoy your meal."),
            ("Bahşiş dahil mi?", "Is the tip included?"),
            ("Paket yapabilir misiniz?", "Can I get this to go, please?"),
            ("Hesabı alabilir miyim?", "Can I have the check, please?"),
        ],
    ),
    (
        "accommodation",
        "travel.phrasebook.cat.accommodation",
        [
            ("Boş odanız var mı?", "Do you have any vacancies?"),
            ("Rezervasyonum var.", "I have a reservation."),
            ("Kahvaltı dahil mi?", "Is breakfast included?"),
            ("Check-out saati kaçta?", "What time is checkout?"),
            ("Wi-Fi şifresi nedir?", "What is the Wi-Fi password?"),
            ("Odamı değiştirebilir miyim?", "Can I change my room?"),
            ("Bagajımı saklayabilir misiniz?", "Can you store my luggage, please?"),
            ("Havluları değiştirebilir misiniz?", "Could you change the towels, please?"),
        ],
    ),
    (
        "socializing",
        "travel.phrasebook.cat.socializing",
        [
            ("Memnun oldum.", "Nice to meet you."),
            ("Nerelisiniz?", "Where are you from?"),
            ("Türkiye'den geliyorum.", "I'm from Turkey."),
            ("Ne iş yapıyorsunuz?", "What do you do?"),
            ("Telefon numaranızı alabilir miyim?", "Can I have your phone number?"),
            ("Sosyal medyanız var mı?", "Do you have social media?"),
            ("İyi eğlenceler!", "Have fun!"),
            ("İyi yolculuklar!", "Have a safe trip!"),
        ],
    ),
]
